# Generated by Django 5.0.3 on 2024-09-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=255)),
                ('codigo_produto', models.CharField(max_length=50, unique=True)),
                ('descricao_produto', models.TextField()),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
